name: Create Release

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3

      # Substitute the values inside module.json
      - uses: microsoft/variable-substitution@v1
        with:
          files: 'module.json'
        env:
          version: ${{ github.ref_name }}
          url: https://github.com/${{ github.repository }}
          manifest: https://github.com/${{ github.repository }}/releases/latest/download/module.json
          download: https://github.com/${{ github.repository }}/releases/download/${{ github.ref_name }}/module.zip
          readme: https://github.com/${{ github.repository }}/blob/main/README.md
          changelog: https://github.com/${{ github.repository }}/blob/main/CHANGELOG.md

      # Zip the files into module.zip
      - run: zip -r ./module.zip module.json LICENSE module/

      # Generate notes
      - uses: CSchoel/release-notes-from-changelog@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          version: ${{ github.ref_name }}
          begin-pattern: '/^## Version ${{ github.ref_name }}/'
          end-pattern: '/^## /'

      # Create the release
      - uses: ncipollo/release-action@v1
        with:
          artifacts: "module.zip,module.json"
          bodyfile: RELEASE.md
